name: Django Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip install -r backend/requirements/django-venv-requirements_2-23-2025.txt
          pip install -r backend/requirements/apt-requirements_2-23-2025.txt

      - name: Wait for AWS RDS to be ready
        run: sleep 20

      - name: Set Environment Variables
        run: |
          echo "DATABASE_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      - name: Make Migrations
        run: python ./backend/manage.py makemigrations

      - name: Migrate Database
        run: python ./backend/manage.py migrate

      - name: Run Tests
        run: python ./backend/manage.py test
